# Generated by Django 6.0.5 on 2026-05-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=50)),
                ('severity_level', models.CharField(max_length=25)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(max_length=500)),
                ('on_going', models.BooleanField(blank=True, null=True)),
                ('victim', models.BooleanField(blank=True, null=True)),
                ('victim_name', models.CharField(blank=True, max_length=100, null=True)),
                ('victim_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('victim_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('accused_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship_to_victim', models.CharField(blank=True, max_length=100, null=True)),
                ('accused_physical_description', models.CharField(blank=True, max_length=100, null=True)),
                ('accused_location', models.CharField(blank=True, max_length=500, null=True)),
                ('detailed_description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='')),
                ('urgent', models.BooleanField(blank=True, null=True)),
                ('sos', models.BooleanField(blank=True, null=True)),
                ('request_authority_reach_out', models.BooleanField(blank=True, null=True)),
                ('valid_details_consent', models.BooleanField()),
                ('privacy_policy_consent', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
