# Generated by Django 6.0.5 on 2026-05-22 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=50)),
                ('severity_level', models.CharField(max_length=25)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(max_length=500)),
                ('on_going', models.BooleanField()),
                ('victim', models.BooleanField()),
                ('victim_name', models.CharField(blank=True, max_length=100, null=True)),
                ('victim_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('victim_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('accused_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship_to_victim', models.CharField(blank=True, max_length=100, null=True)),
                ('accused_physical_description', models.CharField(blank=True, max_length=100, null=True)),
                ('accused_location', models.CharField(blank=True, max_length=500, null=True)),
                ('detailed_description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('urgent', models.BooleanField()),
                ('sos', models.BooleanField()),
                ('request_authority_reach_out', models.BooleanField()),
                ('valid_details_consent', models.BooleanField()),
                ('privacy_policy_consent', models.BooleanField()),
                ('complaint_status', models.CharField(default='pending', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
