# Generated by Django 6.0.5 on 2026-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='on_going',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='request_authority_reach_out',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='sos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='urgent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='victim',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
