# Generated by Django 6.0.5 on 2026-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='is_public',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='public_post_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
