# Generated by Django 6.0.5 on 2026-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
